name=EDP-Platform-FreeRTOS
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=FreeRTOS providers for ESPressio Platform abstractions.
paragraph=Static FreeRTOS execution and synchronization concrete implementations selected through ESPressio Composition.
category=Other
url=https://espressio.org
architectures=*
includes=ESPressio_Platform_FreeRTOS.hpp
depends=EDP-Platform (>=0.1.0 && <0.2.0)
